[package]
name = "tokio-futures-byteorder"
version = "0.2.0"
edition = "2018"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

readme = "README.md"
description = "Asynchronous library for reading/writing numbers in big-endian and little-endian."
repository = "https://github.com/samdenty/tokio-byteorder"

keywords = ["byte", "endian", "big-endian", "little-endian", "tokio"]
categories = ["encoding", "parsing", "asynchronous"]

license = "Unlicense OR MIT"

[badges]
azure-devops = { project = "jonhoo/jonhoo", pipeline = "tokio-byteorder", build = "12" }
codecov = { repository = "jonhoo/tokio-byteorder", branch = "master", service = "github" }


[dependencies]
tokio = { version = "0.2", features = ["io-util"], optional = true }
byteorder = "1.3.2"
futures-io = { version = "0.3.4", optional = true }

[features]
default = ["tokio"]
futures = ["futures-io"]

[dev-dependencies]
tokio = { version = "0.2", features = ["full", "macros"] }
futures-executor = "0.3.4"
